services:
  comfyui:
    image: yanwk/comfyui-boot:cu128-slim
    ports:
      - "8188:8188"
    volumes:
      - ./../models:/root/ComfyUI/models
      - ./../output:/root/ComfyUI/output
      # 任意：Managerで入れたcustom_nodesをホストに残したいなら
      - ./custom_nodes:/root/ComfyUI/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
